description: |
  The default executor allows you to pass in a Python and/or Debian version.
  This will set your job to use one of the CircleCI python convenience images.
  The envuroment will be Python 2.7 with Debian stretch by default.

parameters:
  python-version:
    type: string
    default: "2.7"
  debian-release:
    type: string
    default: "stretch"

docker:
  - image: circleci/python:<<parameters.python-version>>-<<parameters.debian-release>>
    environment:
      PIPENV_VENV_IN_PROJECT: true
